name: 'Auto-close marked issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been closed due to inactivity in over 30 days after being marked for closure.'
          stale-pr-message: 'This pull request has been closed due to inactivity in over 30 days after being marked for closure.'
          days-before-stale: 30
          days-before-close: 30
          stale-issue-label: 'stale'
          exempt-issue-labels: 'awaiting-response, question'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'awaiting-response, question'
